# Generated by Django 2.0.1 on 2018-03-12 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultra_odds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ultrasub',
            old_name='daily_main',
            new_name='ultra_main',
        ),
    ]
