# Generated by Django 2.0.1 on 2018-03-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultra_odds', '0002_auto_20180312_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultrasub',
            name='form_away',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='ultrasub',
            name='form_home',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='ultrasub',
            name='goals_away',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='ultrasub',
            name='goals_home',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='ultrasub',
            name='h2h_away',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='ultrasub',
            name='h2h_draw',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='ultrasub',
            name='h2h_home',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='ultrasub',
            name='missing_players_away',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='ultrasub',
            name='missing_players_home',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='ultrasub',
            name='standings_away',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='ultrasub',
            name='standings_home',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
