# Generated by Django 2.0.1 on 2018-03-12 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily_odds', '0002_dailymain_slip_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysub',
            name='daily_main',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='daily_odds.DailyMain'),
        ),
    ]
