# Generated by Django 2.0.1 on 2018-03-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_odds', '0005_auto_20180318_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymain',
            name='slip_date',
            field=models.DateField(default=None, verbose_name='slip_date'),
        ),
    ]
