# Generated by Django 2.0.1 on 2018-03-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_odds', '0006_auto_20180329_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymain',
            name='slip_date',
            field=models.DateTimeField(default=None, verbose_name='slip_date'),
        ),
    ]
